FROM ubuntu:24.04

RUN apt-get update && apt-get install -y curl apache2-utils siege vim

RUN mkdir /root/.siege && echo "limit = 1000" > /root/.siege/siege.conf

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"